fix(ci/update): Remove myself from the reviewers Since a GitHub token is used to make the pull request I'm the author of it. This means that I cannot be the reviewer - you cannot request a review from the author.
It resulted in the following error when running
the update action:

```
Error: Review cannot be requested from pull request author.
```